name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

permissions:
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Auto green
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          git config --local user.email "1441821178@qq.com"
          git config --local user.name "First-Jim"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "a commit a day keeps your girlfriend away"
          git push
